source ale/init.vim
source asyncrun.vim/init.vim
source fzf.vim/init.vim
source LeaderF/init.vim
source lightline.vim/init.vim
source nerdcommenter/init.vim
source PHP-Indenting-for-VIm/init.vim
source tagbar/init.vim
source vim-bookmarks/init.vim
source vim-fugitive/init.vim
source vim-gitgutter/init.vim
source vim-php-cs-fixer/init.vim
source vim-project/init.vim
source vim-startify/init.vim
source vimagit/init.vim
source vimfiler.vim/init.vim
